# Generated by Django 3.2.2 on 2023-10-12 09:46

import builtins
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='idCliente')),
                ('razonSocial', models.CharField(max_length=256, verbose_name='Razon social')),
                ('cuenta', models.CharField(max_length=6, verbose_name='Numero de cuenta')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('RFC', models.CharField(max_length=18, verbose_name='RFC')),
                ('calle', models.CharField(blank=True, max_length=128, null=True, verbose_name='Calle')),
                ('noExt', models.CharField(blank=True, default='SN', max_length=15, verbose_name='No exterior')),
                ('noInt', models.CharField(blank=True, default='SN', max_length=15, verbose_name='No Interior')),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
                ('municipio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado')),
                ('colonia', models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False, verbose_name='idInventario')),
                ('NombresProducto', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('Descripcion', models.CharField(max_length=200, verbose_name=' Descripcion')),
                ('Categoria', models.CharField(max_length=100, verbose_name='Categoria ')),
                ('NumeroDeSerie', models.CharField(max_length=20, verbose_name=' Numero De Serie')),
                ('CantidadDeStock', models.IntegerField(verbose_name=' Cantidad En Stock')),
                ('PrecioUnitario', models.FloatField(max_length=50, verbose_name=' Precio Unitario')),
                ('PrecioDeCompra', models.FloatField(max_length=50, verbose_name=' Precio De Compra')),
                ('FechaDeCompra', models.DateField(default=datetime.datetime.now, verbose_name='Fecha De Compra')),
                ('NivelDeReordenamiento', models.IntegerField(verbose_name=' Numero De Ordenamiento ')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='idProveedor')),
                ('razonSocial', models.CharField(max_length=256)),
                ('cuenta', models.CharField(max_length=10, unique=True, verbose_name='Cuenta')),
                ('RFC', models.CharField(max_length=18, verbose_name='RFC')),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
                ('municipio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado')),
                ('colonia', models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('activo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Activo')),
                ('representanteLegal', models.CharField(blank=True, max_length=128, null=True, verbose_name='Representante legal')),
            ],
            options={
                'verbose_name': 'Proovedor',
                'verbose_name_plural': 'Proovedores',
                'db_table': 'Proovedor',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='idVenta')),
                ('totalDeVentas', models.FloatField(max_length=50, verbose_name='Total de Venta')),
                ('fechaDeCompra', models.DateField(default=datetime.date.today, verbose_name='Fecha de Compra')),
                ('estatus', models.CharField(max_length=100, verbose_name='Estatus')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.clientes', verbose_name='idCliente')),
                ('colaboradorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name=builtins.id)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='PermisosEdicion',
            fields=[
                ('idPermiso', models.AutoField(primary_key=True, serialize=False, verbose_name='idPermiso')),
                ('comentario', models.CharField(blank=True, max_length=128, null=True, verbose_name='Comentario')),
                ('estatus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Estatus')),
                ('password', models.CharField(blank=True, max_length=18, null=True, verbose_name='Contraseña')),
                ('fechaEdicion', models.DateField(default=datetime.datetime.now, null=True, verbose_name='Fecha de Edición')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='idEmpleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.clientes', verbose_name='idEmpresa')),
            ],
            options={
                'verbose_name': 'PermisosEdicion',
                'verbose_name_plural': 'PermisosEdiciones',
                'db_table': 'PermisosEdicion',
            },
        ),
        migrations.CreateModel(
            name='PermisoInasistencia',
            fields=[
                ('idPermiso', models.AutoField(primary_key=True, serialize=False, verbose_name='idPermiso')),
                ('fechaInasistencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Inisistencia')),
                ('motivo', models.CharField(blank=True, default='', max_length=256, verbose_name='Motivo')),
                ('comentario', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentario')),
                ('estatus', models.CharField(default='PENDIENTE', max_length=64, verbose_name='Estatus')),
                ('fechaCreacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Creacion')),
                ('empleadoo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idEmpleadoo', to=settings.AUTH_USER_MODEL, verbose_name='idEmpleadoo')),
            ],
            options={
                'verbose_name': 'PermisoInasistencia',
                'verbose_name_plural': 'PermisoInasistencias',
                'db_table': 'PermisoInasistencia',
            },
        ),
        migrations.CreateModel(
            name='Llamadas',
            fields=[
                ('idLlamada', models.AutoField(primary_key=True, serialize=False, verbose_name='idLlamada')),
                ('segundos', models.CharField(blank=True, max_length=128, null=True, verbose_name='segundos')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='idEmpleado')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'db_table': 'Llamadas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaDN',
            fields=[
                ('idEmpresaDN', models.AutoField(primary_key=True, serialize=False, verbose_name='idEmpresaDN')),
                ('dn', models.CharField(blank=True, max_length=10, null=True, verbose_name='DN')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.clientes', verbose_name='idEmpresa')),
            ],
            options={
                'verbose_name': 'EmpresaDN',
                'verbose_name_plural': 'EmpresasDNs',
                'db_table': 'EmpresaDN',
            },
        ),
        migrations.CreateModel(
            name='EmpresaAsignada',
            fields=[
                ('idAsignacion', models.AutoField(primary_key=True, serialize=False, verbose_name='idAsignacion')),
                ('comentario', models.CharField(default='PROPIA', max_length=128, verbose_name='Comentario')),
                ('fechaAsignada', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Asignación')),
                ('estatus', models.CharField(default='SIN ESTATUS', max_length=15, verbose_name='Estatus')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='idEmpleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.clientes', verbose_name='idEmpresa')),
            ],
            options={
                'verbose_name': 'EmpresaAsignada',
                'verbose_name_plural': 'EmpresasAsignadas',
                'db_table': 'EmpresaAsignada',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalleVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='idDetalleVenta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precioUnitario', models.FloatField(max_length=50, verbose_name='Precio Unitario')),
                ('precioTotal', models.FloatField(max_length=50, verbose_name='Precio Total')),
                ('fechaDeCompra', models.DateField(default=datetime.date.today, verbose_name='Fecha de Compra')),
                ('inventarioId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.inventario', verbose_name='idInventario')),
                ('ventaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.venta', verbose_name='idVenta')),
            ],
            options={
                'verbose_name': 'DetalleVenta',
                'verbose_name_plural': 'DetalleVentas',
                'db_table': 'DetalleVenta',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False, verbose_name='idCita')),
                ('razonSocial', models.CharField(blank=True, max_length=128, null=True, verbose_name='Razon Social')),
                ('responsable', models.CharField(blank=True, max_length=128, null=True, verbose_name='Responsable')),
                ('fechaAgenda', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha agenda')),
                ('fechaCita', models.DateTimeField(null=True, verbose_name='Fecha Cita')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('estatus', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estatus')),
                ('url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Url')),
                ('empleado_c', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado Cita')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Cita',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False, verbose_name='idAsistencia')),
                ('fechaAsistencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Asistencia')),
                ('estatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='estatus')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idColaborador', to=settings.AUTH_USER_MODEL, verbose_name='idColaborador')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Agendarllamada',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False, verbose_name='idAgenda')),
                ('fechaAgenda', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha agenda')),
                ('fechaLlamada', models.DateTimeField(null=True, verbose_name='Fecha Llamada')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('estatus', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estatus')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario')),
                ('url', models.CharField(blank=True, max_length=128, null=True, verbose_name='Url')),
                ('categoria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Comentario')),
                ('cliente_al', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.clientes', verbose_name='Cliente Agenda')),
                ('user_al', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado Agenda')),
            ],
            options={
                'verbose_name': 'Agendarllamada',
                'verbose_name_plural': 'Agendarllamada',
                'db_table': 'Agendarllamada',
            },
        ),
    ]
