# Generated by Django 3.2.2 on 2023-09-19 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='idCliente')),
                ('razonSocial', models.CharField(max_length=256, verbose_name='Razon social')),
                ('denominacion', models.CharField(blank=True, max_length=6, verbose_name='Denominacion')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('RFC', models.CharField(max_length=18, verbose_name='RFC')),
                ('calle', models.CharField(blank=True, max_length=128, null=True, verbose_name='Calle')),
                ('noExt', models.CharField(blank=True, default='SN', max_length=15, verbose_name='No exterior')),
                ('noInt', models.CharField(blank=True, default='SN', max_length=15, verbose_name='No Interior')),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
                ('municipio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado')),
                ('colonia', models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False, verbose_name='idInventario')),
                ('NombresProducto', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('Descripcion', models.CharField(max_length=200, verbose_name=' Descripcion')),
                ('Categoria', models.CharField(max_length=100, verbose_name='Categoria ')),
                ('NumeroDeSerie', models.CharField(max_length=20, verbose_name=' Numero De Serie')),
                ('CantidadDeStock', models.IntegerField(verbose_name=' Cantidad En Stock')),
                ('PrecioUnitario', models.FloatField(max_length=50, verbose_name=' Precio Unitario')),
                ('PrecioDeCompra', models.FloatField(max_length=50, verbose_name=' Precio De Compra')),
                ('FechaDeCompra', models.DateField(default=datetime.datetime.now, verbose_name='Fecha De Compra')),
                ('NivelDeReordenamiento', models.IntegerField(verbose_name=' Numero De Ordenamiento ')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='idProveedor')),
                ('razonSocial', models.CharField(max_length=256)),
                ('cuenta', models.CharField(max_length=10, unique=True, verbose_name='Cuenta')),
                ('RFC', models.CharField(max_length=18, verbose_name='RFC')),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
                ('municipio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado')),
                ('colonia', models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('activo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Activo')),
                ('representanteLegal', models.CharField(blank=True, max_length=128, null=True, verbose_name='Representante legal')),
            ],
            options={
                'verbose_name': 'Proovedor',
                'verbose_name_plural': 'Proovedores',
                'db_table': 'Proovedor',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='idVenta')),
                ('totalDeVenta', models.FloatField(max_length=50, verbose_name='Total de Venta')),
                ('fechaDeCompra', models.DateField(default=datetime.date.today, verbose_name='Fecha de Compra')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.clientes', verbose_name='idCliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalleVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='idDetalleVenta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precioUnitario', models.FloatField(max_length=50, verbose_name='Precio Unitario')),
                ('precioTotal', models.FloatField(max_length=50, verbose_name='Precio Total')),
                ('fechaDeCompra', models.DateField(default=datetime.date.today, verbose_name='Fecha de Compra')),
                ('inventarioId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.inventario', verbose_name='idInventario')),
                ('ventaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principales.venta', verbose_name='idVenta')),
            ],
            options={
                'verbose_name': 'DetalleVenta',
                'verbose_name_plural': 'DetalleVentas',
                'db_table': 'DetalleVenta',
            },
        ),
    ]
