# Generated by Django 3.2.2 on 2023-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comentario',
            field=models.CharField(default=1, max_length=250, verbose_name='Estatus'),
            preserve_default=False,
        ),
    ]
