# Generated by Django 3.2.2 on 2023-09-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='totalDeVenta',
            new_name='totalDeVentas',
        ),
    ]
