# Generated by Django 3.2.2 on 2023-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0002_rename_totaldeventa_venta_totaldeventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estatus',
            field=models.CharField(default=1, max_length=100, verbose_name='Estatus'),
            preserve_default=False,
        ),
    ]
