# Generated by Django 3.2.2 on 2023-10-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0003_agendarllamada_cita_empresaasignada_empresadn_llamadas_permisosedicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='colaboradorId',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cuenta',
            field=models.CharField(max_length=6, verbose_name='Numero de cuenta'),
        ),
    ]
