# Generated by Django 3.2.2 on 2023-09-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0003_venta_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='denominacion',
            new_name='cuenta',
        ),
    ]
