# Generated by Django 3.2.2 on 2023-08-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0003_clientes_proovedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Proovedor',
        ),
    ]
