# Generated by Django 3.2.2 on 2023-09-27 11:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principales', '0003_venta_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False, verbose_name='idAsistencia')),
                ('fechaAsistencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Asistencia')),
                ('estatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='estatus')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idColaborador', to=settings.AUTH_USER_MODEL, verbose_name='idColaborador')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'Asistencia',
            },
        ),
    ]
