# Generated by Django 3.2.2 on 2023-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0004_venta_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cuenta',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Cuenta'),
            preserve_default=False,
        ),
    ]
