# Generated by Django 3.2.2 on 2023-10-10 16:41

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principales', '0004_auto_20231010_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='colaboradorId',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='login.user', verbose_name=builtins.id),
            preserve_default=False,
        ),
    ]
