# Generated by Django 3.2.2 on 2023-10-10 12:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principales', '0004_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoInasistencia',
            fields=[
                ('idPermiso', models.AutoField(primary_key=True, serialize=False, verbose_name='idPermiso')),
                ('fechaInasistencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Inisistencia')),
                ('motivo', models.CharField(blank=True, default='', max_length=256, verbose_name='Motivo')),
                ('comentario', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentario')),
                ('estatus', models.CharField(default='PENDIENTE', max_length=64, verbose_name='Estatus')),
                ('fechaCreacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Creacion')),
                ('empleadoo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idEmpleadoo', to=settings.AUTH_USER_MODEL, verbose_name='idEmpleadoo')),
            ],
            options={
                'verbose_name': 'PermisoInasistencia',
                'verbose_name_plural': 'PermisoInasistencias',
                'db_table': 'PermisoInasistencia',
            },
        ),
    ]
