# Generated by Django 3.2.2 on 2023-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principales', '0004_auto_20230828_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=256)),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('RFC', models.CharField(max_length=18, verbose_name='RFC')),
                ('calle', models.CharField(blank=True, max_length=128, null=True, verbose_name='Calle')),
                ('noExt', models.CharField(blank=True, default='SN', max_length=15, verbose_name='No exterior')),
                ('noInt', models.CharField(blank=True, default='SN', max_length=15, verbose_name='No Interior')),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
                ('municipio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado')),
                ('colonia', models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono 1')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=256)),
                ('cuenta', models.CharField(max_length=10, unique=True, verbose_name='Cuenta')),
                ('RFC', models.CharField(max_length=18, verbose_name='RFC')),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
                ('municipio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado')),
                ('colonia', models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('activo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Activo')),
                ('representanteLegal', models.CharField(blank=True, max_length=128, null=True, verbose_name='Representante legal')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proovedor',
                'verbose_name_plural': 'Proovedores',
                'db_table': 'Proovedor',
            },
        ),
    ]
