# Generated by Django 3.2.2 on 2023-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0004_rename_denominacion_clientes_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuenta',
            field=models.CharField(blank=True, max_length=6, verbose_name='Numero de cuenta'),
        ),
    ]
