# Generated by Django 3.2.2 on 2023-09-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0005_clientes_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cuenta',
        ),
    ]
