# Generated by Django 3.2.2 on 2023-08-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0005_clientes_proovedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='razonSocial',
            field=models.CharField(max_length=256, verbose_name='Razon social'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
    ]
