# Generated by Django 3.2.2 on 2023-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0006_auto_20230831_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('Descripcion', models.CharField(max_length=200, verbose_name=' Descripcion')),
                ('Categoria', models.CharField(max_length=100, verbose_name='Categoria ')),
                ('NumeroDeSerie', models.CharField(max_length=20, verbose_name=' Numero De Serie')),
                ('CantidadEnStock', models.IntegerField(max_length=50, verbose_name=' Cantidad En Stock')),
                ('PrecioUnitario', models.FloatField(max_length=50, verbose_name=' Precio Unitario')),
                ('PrecioDeCompra', models.FloatField(max_length=50, verbose_name=' Precio De Compra')),
                ('FechaDeCompra', models.DateTimeField(max_length=9, verbose_name='Fecha De Compra')),
                ('NiverDeReordenamiento', models.IntegerField(max_length=50, verbose_name=' Numero De Ordenamiento ')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'Inventario',
            },
        ),
    ]
