# Generated by Django 3.2.2 on 2023-09-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0006_remove_clientes_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cuenta',
            field=models.CharField(default=3, max_length=10, unique=True, verbose_name='Cuenta'),
            preserve_default=False,
        ),
    ]
