# Generated by Django 3.2.2 on 2023-09-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0008_auto_20230911_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='NiverDeReordenamiento',
            new_name='NivelDeReordenamiento',
        ),
    ]
