# Generated by Django 3.2.2 on 2023-09-12 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0009_rename_niverdereordenamiento_inventario_niveldereordenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='FechaDeCompra',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha De Compra'),
        ),
    ]
