# Generated by Django 3.2.2 on 2023-09-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0010_alter_inventario_fechadecompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='NombreProducto',
            new_name='NombresProducto',
        ),
    ]
