# Generated by Django 3.2.2 on 2023-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principales', '0012_rename_cantidadenstock_inventario_cantidaddestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='denominacion',
            field=models.CharField(blank=True, max_length=6, verbose_name='Denominacion'),
        ),
    ]
