# Generated by Django 3.2.2 on 2023-08-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_codigospostales_colonia2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigospostales',
            options={},
        ),
        migrations.AlterModelTable(
            name='codigospostales',
            table=None,
        ),
    ]
