# Generated by Django 3.2.2 on 2023-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20230831_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigospostales',
            name='Colonia3',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia3'),
        ),
        migrations.AlterField(
            model_name='codigospostales',
            name='Colonia2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia2'),
        ),
    ]
