# Generated by Django 3.2.2 on 2023-08-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20230831_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigospostales',
            name='Colonia2',
        ),
        migrations.RemoveField(
            model_name='codigospostales',
            name='Colonia3',
        ),
    ]
