# Generated by Django 3.2.2 on 2023-08-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20230831_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigospostales',
            options={'verbose_name': 'CodigoPostal', 'verbose_name_plural': 'CodigosPotales'},
        ),
        migrations.AlterModelTable(
            name='codigospostales',
            table='CodigosPostales',
        ),
    ]
