# Generated by Django 3.2.2 on 2023-09-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_estados_codigospostales_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigospostales',
            old_name='Estado',
            new_name='Estados',
        ),
    ]
