# Generated by Django 3.2.2 on 2023-09-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_rename_estado_codigospostales_estados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigospostales',
            old_name='Estados',
            new_name='Estado',
        ),
    ]
