from django.test import TestCase

import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'sicov.settings')

from django.core.wsgi import get_wsgi_application

application = get_wsgi_application()
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
# Create your tests here.
from core.login.models import User
from core.erp.models import EmpleadoAsignado


#
# for i in User.objects.all():
#     u = User.objects.get(pk=i.id)
#     u.set_password(i.password)
#     u.is_active = True
#     u.save()


def guardarEmpleadoEncargado(empleado, coordinador):
    try:
        emp = User.objects.get(username=empleado)
        coor = User.objects.get(username=coordinador)
        asignado = EmpleadoAsignado()
        asignado.empleado = emp
        asignado.encargado = coor
        asignado.save()
    except Exception as e:
        print(e)


guardarEmpleadoEncargado("FONTIVEROSM", "LROMANH")
guardarEmpleadoEncargado("LROMANH", "LROMANH")
guardarEmpleadoEncargado("USANCHEZR", "EPINEDAG")
guardarEmpleadoEncargado("EALONSOG", "FONTIVEROSM")
guardarEmpleadoEncargado("JCHENE", "EPINEDAG")
guardarEmpleadoEncargado("SPALMAH", "FONTIVEROSM")
guardarEmpleadoEncargado("ARODRIGUEZT", "AESQUIVELL")
guardarEmpleadoEncargado("ALOPEZM", "FONTIVEROSM")
guardarEmpleadoEncargado("CANAYAV", "FONTIVEROSM")
guardarEmpleadoEncargado("RMORENOU", "FONTIVEROSM")
guardarEmpleadoEncargado("TMORAP", "FONTIVEROSM")
guardarEmpleadoEncargado("ASALGADOC", "FONTIVEROSM")
guardarEmpleadoEncargado("ASOLISM", "FONTIVEROSM")
guardarEmpleadoEncargado("CARAGONR", "EPINEDAG")
guardarEmpleadoEncargado("DESPARZAV", "FONTIVEROSM")
guardarEmpleadoEncargado("VMOLINAG", "FONTIVEROSM")
guardarEmpleadoEncargado("JGONZALEZG", "FONTIVEROSM")
guardarEmpleadoEncargado("SPORRAS H", "FONTIVEROSM")
guardarEmpleadoEncargado("KGUZMANG", "FONTIVEROSM")
guardarEmpleadoEncargado("JGARDUÑOS", "EPINEDAG")
guardarEmpleadoEncargado("FMARTINEZR", "FONTIVEROSM")
guardarEmpleadoEncargado("XCARRASCOR", "FONTIVEROSM")
guardarEmpleadoEncargado("MFLORESG", "LROMANH")
guardarEmpleadoEncargado("CCUREÑOL", "FONTIVEROSM")
guardarEmpleadoEncargado("JGALICIAS", "FONTIVEROSM")
guardarEmpleadoEncargado("AGALICIAS", "FONTIVEROSM")
guardarEmpleadoEncargado("knt", "FONTIVEROSM")
guardarEmpleadoEncargado("LCASTILLOG", "FONTIVEROSM")
guardarEmpleadoEncargado("ANIEVESA", "FONTIVEROSM")
guardarEmpleadoEncargado("KFIERRON", "FONTIVEROSM")
guardarEmpleadoEncargado("DGONZALEZA", "FONTIVEROSM")
guardarEmpleadoEncargado("ALOPEZB", "FONTIVEROSM")
guardarEmpleadoEncargado("DVIDALL", "FONTIVEROSM")
guardarEmpleadoEncargado("AORDAZR", "FONTIVEROSM")
guardarEmpleadoEncargado("JORTIZL", "EPINEDAG")
guardarEmpleadoEncargado("JORTIZL", "EPINEDAG")
guardarEmpleadoEncargado("ACHAVEZC", "JUAN ORTIZ LUNA")
guardarEmpleadoEncargado("MMIJESA", "FONTIVEROSM")
guardarEmpleadoEncargado("JBUSTAMANTER", "FONTIVEROSM")
guardarEmpleadoEncargado("GSÁNCHEZE", "EPINEDAG")
guardarEmpleadoEncargado("TLEIJAS", "EPINEDAG")
guardarEmpleadoEncargado("FGONZALEZC", "FONTIVEROSM")
guardarEmpleadoEncargado("JVIVEROSS", "FONTIVEROSM")
guardarEmpleadoEncargado("CORNELASR", "EPINEDAG")
guardarEmpleadoEncargado("AGONZALEZF", "FONTIVEROSM")
guardarEmpleadoEncargado("KGONZALEZC", "FONTIVEROSM")
guardarEmpleadoEncargado("ARAMIREZL", "FONTIVEROSM")
guardarEmpleadoEncargado("LGARCÍAA", "FONTIVEROSM")
guardarEmpleadoEncargado("KCHAVEZD", "FONTIVEROSM")
guardarEmpleadoEncargado("OLLANOSG", "JGARDUÑOS")
guardarEmpleadoEncargado("JRIOSC", "FONTIVEROSM")
guardarEmpleadoEncargado("ECANOC", "FONTIVEROSM")
guardarEmpleadoEncargado("MHERNANDEZR", "JGARDUÑOS")
guardarEmpleadoEncargado("AGERONIMOE", "FONTIVEROSM")
guardarEmpleadoEncargado("EPEREZR", "FONTIVEROSM")
guardarEmpleadoEncargado("AESQUIVELL", "LROMANH")
guardarEmpleadoEncargado("MREYEST", "FONTIVEROSM")
guardarEmpleadoEncargado("GGONZALEZG", "FONTIVEROSM")
guardarEmpleadoEncargado("DHERNANDEZH", "LROMANH")
guardarEmpleadoEncargado("DRAMOSG", "FONTIVEROSM")
guardarEmpleadoEncargado("CGUTIERREZG", "LROMANH")
guardarEmpleadoEncargado("MATENCOMILAA", "LROMANH")
guardarEmpleadoEncargado("knt", "FONTIVEROSM")
guardarEmpleadoEncargado("APINEDAG", "JGARDUÑOS")
guardarEmpleadoEncargado("JJIMENEZO", "FONTIVEROSM")
guardarEmpleadoEncargado("MSALDANAG", "FONTIVEROSM")
guardarEmpleadoEncargado("MLOPEZO", "FONTIVEROSM")
guardarEmpleadoEncargado("GANDRADET", "LROMANH")
guardarEmpleadoEncargado("APONCER", "JGARDUÑOS")
guardarEmpleadoEncargado("FCRIVELLIC", "FONTIVEROSM")
guardarEmpleadoEncargado("JMONDRAGÓNL", "LROMANH")
guardarEmpleadoEncargado("APONCER", "FONTIVEROSM")
guardarEmpleadoEncargado("EJIMENEZD", "JGARDUÑOS")
guardarEmpleadoEncargado("EHURTADOL", "AESQUIVELL")
guardarEmpleadoEncargado("ERINCONZ", "AESQUIVELL")
guardarEmpleadoEncargado("LSALMERONB", "AESQUIVELL")
guardarEmpleadoEncargado("RFUENTESV", "AESQUIVELL")
guardarEmpleadoEncargado("DATILANOG", "LROMANH")
guardarEmpleadoEncargado("FCHINASD", "AESQUIVELL")
guardarEmpleadoEncargado("JHERNANDEZP", "AESQUIVELL")
guardarEmpleadoEncargado("LSANCHEZM", "AESQUIVELL")
guardarEmpleadoEncargado("FDOMINGUEZV", "AESQUIVELL")
guardarEmpleadoEncargado("CALBINOG", "AESQUIVELL")
guardarEmpleadoEncargado("DVIDALL", "FONTIVEROSM")
guardarEmpleadoEncargado("RSANTOSG", "AESQUIVELL")
guardarEmpleadoEncargado("Secuencia", "TLEIJAS")
guardarEmpleadoEncargado("ABARRERAC", "AESQUIVELL")
guardarEmpleadoEncargado("FARTUZAM", "AESQUIVELL")
guardarEmpleadoEncargado("YAVENDANOB", "AESQUIVELL")
guardarEmpleadoEncargado("GVICENTEV", "AESQUIVELL")
guardarEmpleadoEncargado("BDIAZD", "FONTIVEROSM")
guardarEmpleadoEncargado("VAGUILARV", "TLEIJAS")
guardarEmpleadoEncargado("DESCALONAC", "TLEIJAS")
guardarEmpleadoEncargado("LRUIZR", "AESQUIVELL")
guardarEmpleadoEncargado("EHURTADOL", "TLEIJAS")
guardarEmpleadoEncargado("OMARTINEZE", "EPINEDAG")
guardarEmpleadoEncargado("DMORALESR", "LROMANH")
guardarEmpleadoEncargado("DHERNANDEZH", "LROMANH")
guardarEmpleadoEncargado("MREYEST", "LROMANH")
guardarEmpleadoEncargado("JJIMENEZO", "LROMANH")
guardarEmpleadoEncargado("KCERVANTESG", "FONTIVEROSM")
guardarEmpleadoEncargado("BDIAZD", "FONTIVEROSM")
guardarEmpleadoEncargado("AMEJIAG", "TLEIJAS")
guardarEmpleadoEncargado("DATILANOG", "FONTIVEROSM")
guardarEmpleadoEncargado("LPEREZS", "JGARDUÑOS")
guardarEmpleadoEncargado("ETREJOH", "TLEIJAS")
guardarEmpleadoEncargado("EMARTINEZL", "CARAGONR")
guardarEmpleadoEncargado("AVEGAG", "JGARDUÑOS")
guardarEmpleadoEncargado("BPENAR", "ITRUJILLOS")
guardarEmpleadoEncargado("DARIASM", "JGARDUÑOS")
guardarEmpleadoEncargado("BVELAZQUEZC", "JGARDUÑOS")
guardarEmpleadoEncargado("BVELAZQUEZC", "JGARDUÑOS")
guardarEmpleadoEncargado("AOROZCOH", "JGARDUÑOS")
guardarEmpleadoEncargado("DARIASM", "JGARDUÑOS")
guardarEmpleadoEncargado("DARIASM", "JGARDUÑOS")
guardarEmpleadoEncargado("AOROZCOH", "JGARDUÑOS")
guardarEmpleadoEncargado("AREYESO", "LROMANH")
